# Generated by Django 6.0.4 on 2026-05-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WifiMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('basement', '地下室'), ('floor1', '一樓')], default='basement', max_length=32)),
                ('point_id', models.CharField(max_length=64)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('ssid', models.CharField(blank=True, max_length=128, null=True)),
                ('bssid', models.CharField(blank=True, max_length=32, null=True)),
                ('channel', models.IntegerField(blank=True, null=True)),
                ('rssi', models.FloatField()),
                ('rx_rate', models.FloatField(blank=True, null=True)),
                ('tx_rate', models.FloatField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
