# Generated by Django 6.0.4 on 2026-05-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifimeasurement',
            name='download_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='metric_type',
            field=models.CharField(default='rssi', max_length=20),
        ),
        migrations.AlterField(
            model_name='wifimeasurement',
            name='rssi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
