# Generated by Django 6.0.4 on 2026-05-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0002_wifimeasurement_download_mbps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifimeasurement',
            name='ap_mac',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='ap_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='client_mac',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='radio_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wifimeasurement',
            name='bssid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wifimeasurement',
            name='floor',
            field=models.CharField(choices=[('basement', '地下室'), ('floor1', '一樓'), ('floor2', '二樓'), ('floor3', '三樓'), ('floor4', '四樓'), ('floor5', '五樓'), ('floor6', '六樓')], default='basement', max_length=32),
        ),
        migrations.AlterField(
            model_name='wifimeasurement',
            name='point_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
